### ISSUE TITLE
Relative paths in CSS do not behave the same as wlogout

### ISSUE THREAD

**Issue by Fxzzi** [AMNatty/wleave#2]
In CSS, the relative paths should be relative to the location of the `style.css`. This is how it works in wlogout. However in wleave, it seems as though the path may be relative to the executable for some reason. This means you are unable to reference images next to the `style.css` without a full path. This will cause issues with usernames being different.

The paths should be relative to the css file.

**Comment by AMNatty** [comment]
I fixed this in https://github.com/AMNatty/wleave/commit/d7e2e88a409d35bcb8d205f0b7482d179cfd4b3b. If the problem persists, feel free to reopen the issue

**Comment by Fxzzi** [comment]
Much love and happy holidays!

**Comment by Fxzzi** [comment]
Hey again, sorry for bothering on New Years Eve lol but it seems the "update dependencies" commit a3d2fbb has broken navigation in wleave. I can no longer use the arrow keys to move between options, however keybindings still work.

**Comment by AMNatty** [comment]
Oh yeah, tabbing as well. I think I missed up event propagation when updating gtk. I've pushed a fix in https://github.com/AMNatty/wleave/commit/619730e665b0d02c7709ea40bee798ecd4d51da4

**Comment by Fxzzi** [comment]
Amazing! Thanks so much and happy new years
