### ISSUE TITLE
Feature request: hide UI before launching command

### ISSUE THREAD

**Issue by Schnouki** [AMNatty/wleave#5]
Hi there,

First, thanks for wleave, it's really nice :)

I'm often using wleave to start [swaylock-effects](https://github.com/jirutka/swaylock-effects) (a fork of swaylock with fancy effects). Swaylock-effects is configured to show a blurred, greyscaled screenshot while active; the only issue is that that screenshot is taken *before* wleave exits, so instead of showing my desktop, it shows the wleave UI.

Would it be possible to add an option to hide the wleave UI before starting the command? (Or to do it all the time without an option if that makes more sense?)
Or would you be interested in merging a PR implementing this if I manage to do it myself? (I'm extremely new to Rust and Wayland programming 😅)

Thanks!

**Comment by AMNatty** [comment]
Sounds good, I can take on this task and also implement a delay CLI argument for adjusting the time between a window hiding and executing a command

**Comment by Schnouki** [comment]
Wonderful, thanks a lot! :clap: :clap:

**Comment by Schnouki** [comment]
@AMNatty I think this broke `--close-on-lost-focus`, though: when the UI is hidden and delay is started, focus switches to something else, closing wleave without starting the command :/

**Comment by AMNatty** [comment]
Oh yes, that's definitely an oversight on my side, I'll quickly push a fix
